###### Name:- Manis Nagpal
Email:- mansinagpal786@gmail.com

Phase 1

1) Webscrape the provided URL - IMDB dataset:

https://www.imdb.com/search/title/?genres=action&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=f11158cc-b50b-4c4d-b0a2-40b32863395b&pf_rd_r=XZ8X52H1R40B7KG5SNZ9&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_1

2) Store the entire data in two different CSV files as per the given fields:

The first CSV file data contains :

Sno, Movie Name, Director Name, Duration, year, ratings, Metascore

Bifurcate the Director field into subfields as per the number of directors of the movie belongs to such as Director1, director2

The second CSV file contains the following:

Movie Name, stars, votes, Genre, Gross collection, popularity, Certification

Bifurcate the stars field into 4 subfields as per the number of stars worked in the movie such as star1, star2, star3, star4

Bifurcate the genre into 3 subfields as per the number of genres the movie belongs to such as :

Genre1, genre2, genre3

### Import packages

In [1]:
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.common.by import By
from tqdm import tqdm
import warnings
warnings.filterwarnings("ignore")
from time import sleep
from random import randint
import numpy as np
import pandas as pd
import csv
import sqlite3

In [2]:
# send request to our imdb url
url = 'https://www.imdb.com/search/title/?genres=action&sort=user_rating,desc&title_type=feature&num_votes=25000,&pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=f11158cc-b50b-4c4d-b0a2-40b32863395b&pf_rd_r=XZ8X52H1R40B7KG5SNZ9&pf_rd_s=right-6&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_gnr_1'
response = requests.get(url)
print(response)

<Response [200]>


In [3]:
# scrapping code to collect the data in csv file

Sno=[]
MoviesName=[]
Director_1=[]
Director_2=[]
Director_3=[]
Duration=[]
Metascore=[]
Year=[]
Ratings=[]
   
pages = np.arange(1,1750,50)


for page in  tqdm(pages):
    
    page = requests.get("https://www.imdb.com/search/title/?title_type=feature&num_votes=25000,&genres=action&sort=user_rating,desc&start=" + str(page) + "&ref_=adv_nxt")
  
    soup=BeautifulSoup(page.text, 'html.parser')
  
    movies=soup.find('div',class_="lister-list").find_all('div',class_='lister-item-content')
  
    sleep(2)
    
    for movie in movies:
        sno=movie.find('h3' ,class_="lister-item-header").span.text.strip('.').replace(',','')
        Sno.append(int(sno))
        movie_name=movie.find('h3' ,class_="lister-item-header").a.text
        MoviesName.append(movie_name)
        director=movie.find('p',class_="").get_text(strip=True).split('|')[0]
        if len(director.split(','))==3:
            director_1=director.split(',')[0].strip(' Directors: ')
            director_2=director.split(',')[1]
            director_3=director.split(',')[2]
            Director_1.append(director_1)
            Director_2.append(director_2)
            Director_3.append(director_3)
        
        elif len(director.split(','))==2:
            director_1=director.split(',')[0].strip(' Directors: ')
            director_2=director.split(',')[1]
            Director_1.append(director_1)
            Director_2.append(director_2)
            Director_3.append(np.nan)
            
            
        else:
            director_1=director.strip(' Directors: ')
            Director_1.append(director_1)
            Director_2.append(np.nan)
            Director_3.append(np.nan)
            
        
        duration=movie.find('span',class_="runtime").text.strip(' min')
        Duration.append(duration)
        year=movie.find('span',class_="lister-item-year text-muted unbold").text.strip('(I) ').strip('()')
        Year.append(year)
        ratings=movie.find('div', class_="inline-block ratings-imdb-rating").strong.text.strip('.')
        Ratings.append(ratings)
        try:
            metascore=movie.find('div', class_="inline-block ratings-metascore").span.get_text(strip=True)
            Metascore.append(metascore)
        except Exception as e:
            metascore=np.nan
            Metascore.append(metascore)
        
print(Sno,MoviesName,Director_1,Director_2,Director_3,Duration,Year,Ratings,Metascore)

100%|██████████| 35/35 [02:34<00:00,  4.42s/it]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 22

In [4]:
# check the length of  collected data
print(len(Sno))

1750


In [6]:
Director_1

['Joaquim Dos San',
 'Christopher Nolan',
 'Peter Jackson',
 'Christopher Nolan',
 'Peter Jackson',
 'Peter Jackson',
 'Lana Wachowsk',
 'Irvin Kershn',
 'Sudha Kongara',
 'James Cameron',
 'George Luca',
 'Akira Kurosawa',
 'Masaki Kobayash',
 'Hanu Raghavapud',
 'Luc Besson',
 'Ridley S',
 'Bob Persich',
 'Steven Spielberg',
 'Anthony Ru',
 'Anthony Ru',
 'Park Chan-wook',
 'Christopher Nolan',
 'James Cameron',
 'Lokesh Kanagaraj',
 'Vetrimaaran',
 'Joseph Kosinsk',
 'Michael Mann',
 'Richard Marquand',
 'Hayao Miyazak',
 'Alfred Hitchcock',
 'Rishab Shetty',
 'Nitesh Tiwa',
 'Lokesh Kanagaraj',
 'Ram Kuma',
 'Prashanth Neel',
 'Vishnuvardhan',
 'James Gunn',
 'Jon Wa',
 'Steven Spielberg',
 'Steven Spielberg',
 'Sam Mend',
 'Christopher Nolan',
 'Quentin Tarantin',
 'John McTiernan',
 'James McTeigu',
 'Haruo Sotozak',
 'Akira Kurosawa',
 'Anurag Kashyap',
 'Akira Kurosawa',
 'Gaya',
 'S.S. Rajamoul',
 'Prashanth Neel',
 'Buster Keaton',
 'Aditya Dha',
 'Sukuma',
 'Alper Cagla',
 '

In [7]:
Director_2

['Kemp Powers',
 nan,
 nan,
 nan,
 nan,
 nan,
 'Lilly Wachowski',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Peter Ramsey',
 nan,
 'Joe Russo',
 'Joe Russo',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Pushkar',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Chris Sanders',
 nan,
 nan,
 nan,
 'Kazuya Tsurumaki',
 'Mehmet Tutkun',
 nan,
 'Buster Keaton',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Ross Stewart',
 'Alan Mak',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'William Keighley',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Daniel Scheinert',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'Jo

In [8]:
df= pd.DataFrame({'Name':MoviesName,'Director_1':Director_1,'Director_2':Director_2,'Director_3':Director_3,'Duration':Duration,'Metascore':Metascore,'Year':Year,'Ratings':Ratings})

In [9]:
df

Name         Director_1  \
0                   Spider-Man: Across the Spider-Verse    Joaquim Dos San   
1                                       The Dark Knight  Christopher Nolan   
2         The Lord of the Rings: The Return of the King      Peter Jackson   
3                                             Inception  Christopher Nolan   
4     The Lord of the Rings: The Fellowship of the Ring      Peter Jackson   
...                                                 ...                ...   
1745                                        Heropanti 2         Ahmed Khan   
1746                                             Laxmii     Raghava Lawren   
1747                                  Alone in the Dark           Uwe Boll   
1748                                      The Prototype      Marcelo Grion   
1749                                  House of the Dead           Uwe Boll   

               Director_2          Director_3 Duration Metascore  Year Ratings  
0             Kemp Powers  Justin K. Thompson      140        86  2023     9.0  
1                     NaN                 NaN      152        84  2008     9.0  
2                     NaN                 NaN      201        94  2003     9.0  
3                     NaN                 NaN      148        74  2010     8.8  
4                     NaN                 NaN      178        92  2001     8.8  
...                   ...                 ...      ...       ...   ...     ...  
1745                  NaN                 NaN      145       NaN  2022     2.5  
1746  Balakrishnan Thevar                 NaN      141       NaN  2020     2.5  
1747                  NaN                 NaN       99         9  2005     2.4  
1748                  NaN                 NaN       97       NaN  2022     2.4  
1749                  NaN                 NaN       90        15  2003     2.1  

[1750 rows x 8 columns]

In [11]:
df.to_csv('Movies_1.csv')

In [12]:
# scrapping code to collect the data for 2nd csv file.

MoviesName = []
Stars_1 = []
Stars_2 = []
Stars_3 = []
Stars_4 = []
Votes = []
Gross = []
Genre_1 = []
Genre_2 = []
Genre_3 = []
Certification = []
Popularity = []

pages = np.arange(1, 1750, 50)

for page in  tqdm(pages):
    url = "https://www.imdb.com/search/title/?title_type=feature&num_votes=25000,&genres=action&sort=user_rating,desc&start={}&ref_=adv_nxt".format(page)
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    movies = soup.find('div', class_="lister-list").find_all('div', class_='lister-item-content')
    #sleep(1)

    for movie in movies:
        movie_name = movie.find('h3', class_="lister-item-header").a.text
        MoviesName.append(movie_name)

        stars = movie.find('p', class_="").get_text(strip=True).split('|')[1].split(',')
        Stars_1.append(stars[0].strip(' Stars: '))
        Stars_2.append(stars[1].strip() if len(stars) >= 2 else np.nan)
        Stars_3.append(stars[2].strip() if len(stars) >= 3 else np.nan)
        Stars_4.append(stars[3].strip() if len(stars) >= 4 else np.nan)

        vote = movie.find('p', class_="sort-num_votes-visible").get_text(strip=True).split('|')[0][6:]
        Votes.append(vote)

        genre = movie.find('span', class_="genre").get_text(strip=True).split(',')
        
        Genre_1.append(genre[0].strip() if len(genre) >= 1 else np.nan)
        Genre_2.append(genre[1].strip() if len(genre) >= 2 else np.nan)
        Genre_3.append(genre[2].strip() if len(genre) >= 3 else np.nan)

        try:
            gross = movie.find('p', class_="sort-num_votes-visible").get_text(strip=True).split('|')[1][6:].replace('$', '').replace('M', '')
        except IndexError:
            gross = np.nan
        Gross.append(gross)

        try:
            certificate = movie.find('span', class_="certificate").text
        except AttributeError:
            certificate = np.nan
        Certification.append(certificate)
    
        href=movie.find('h3' ,class_="lister-item-header").a.get('href')
        popularity_url=  f"https://www.imdb.com{href}"
        # Connecting to the webdriver
        # Create ChromeDriver instance using WebDriverManager
        driver = webdriver.Chrome()
        # Opening www.imdb.comin in chrome browser
        driver.get(popularity_url)
        try:
            pop=driver.find_element(By.XPATH,'//*[@id="__next"]/main/div/section[1]/section/div[3]/section/section/div[2]/div[2]/div/div[3]/a/span/div/div[2]/div[1]')
            Popularity.append(pop.text)
            
        except NoSuchElementException:
            Popularity.append(np.nan)  
        

print(MoviesName,Stars_1,Stars_2,Stars_3,Stars_4,Votes,Gross,Genre_1,Genre_2,Genre_3,Certification,Popularity)
# Close the WebDriver
driver.close()

100%|██████████| 35/35 [4:18:51<00:00, 443.77s/it]  


['Spider-Man: Across the Spider-Verse', 'The Dark Knight', 'The Lord of the Rings: The Return of the King', 'Inception', 'The Lord of the Rings: The Fellowship of the Ring', 'The Lord of the Rings: The Two Towers', 'The Matrix', 'Star Wars: Episode V - The Empire Strikes Back', 'Soorarai Pottru', 'Terminator 2: Judgment Day', 'Star Wars', 'Shichinin no samurai', 'Seppuku', 'Sita Ramam', 'Léon', 'Gladiator', 'Spider-Man: Into the Spider-Verse', 'Raiders of the Lost Ark', 'Avengers: Endgame', 'Avengers: Infinity War', 'Oldeuboi', 'The Dark Knight Rises', 'Aliens', 'Kaithi', 'Asuran', 'Top Gun: Maverick', 'Heat', 'Star Wars: Episode VI - Return of the Jedi', 'Mononoke-hime', 'North by Northwest', 'Kantara', 'Dangal', 'Vikram', 'Ratsasan', 'K.G.F: Chapter 2', 'Shershaah', 'Guardians of the Galaxy Vol. 3', 'Spider-Man: No Way Home', 'Jurassic Park', 'Indiana Jones and the Last Crusade', '1917', 'Batman Begins', 'Kill Bill: Vol. 1', 'Die Hard', 'V for Vendetta', 'Kimetsu no Yaiba: Mugen Ress

In [13]:
# check the length of  collected data
print(len(MoviesName))

1750


In [20]:
df1= pd.DataFrame({'Popular':Popularity,'Name':MoviesName,'Stars_1': Stars_1, 'Stars_2':Stars_2, 'Stars_3':Stars_3, 'Stars_4':Stars_4, 'Votes': Votes, 'Genre_1':Genre_1, 'Genre_2':Genre_2, 'Genre_3':Genre_3, 'Gross':Gross, 'Certification':Certification})

In [21]:
df1

Popular                                               Name  \
0          1                Spider-Man: Across the Spider-Verse   
1         84                                    The Dark Knight   
2        324      The Lord of the Rings: The Return of the King   
3         80                                          Inception   
4        170  The Lord of the Rings: The Fellowship of the Ring   
...      ...                                                ...   
1745     NaN                                        Heropanti 2   
1746     NaN                                             Laxmii   
1747     NaN                                  Alone in the Dark   
1748     NaN                                      The Prototype   
1749     NaN                                  House of the Dead   

                Stars_1               Stars_2            Stars_3  \
0          hameik Moore      Hailee Steinfeld  Brian Tyree Henry   
1        Christian Bale          Heath Ledger      Aaron Eckhart   
2           Elijah Wood       Viggo Mortensen       Ian McKellen   
3     Leonardo DiCaprio  Joseph Gordon-Levitt        Elliot Page   
4           Elijah Wood          Ian McKellen      Orlando Bloom   
...                 ...                   ...                ...   
1745       Tiger Shroff   Nawazuddin Siddiqui       Tara Sutaria   
1746         Akshay Kum          Kiara Advani      Sharad Kelkar   
1747    Christian Slate             Tara Reid      Stephen Dorff   
1748   Mark Vasconcello        Frank Spinelli   Victoria De Mare   
1749    Jonathan Cherry          Tyron Leitso       Clint Howard   

                  Stars_4      Votes    Genre_1    Genre_2    Genre_3   Gross  \
0       Luna Lauren Velez    125,082  Animation     Action  Adventure     NaN   
1           Michael Caine  2,725,569     Action      Crime      Drama  534.86   
2           Orlando Bloom  1,891,064     Action  Adventure      Drama  377.85   
3            Ken Watanabe  2,419,065     Action  Adventure     Sci-Fi  292.58   
4               Sean Bean  1,919,680     Action  Adventure      Drama  315.54   
...                   ...        ...        ...        ...        ...     ...   
1745    Amber Doig-Thorne     27,009     Action     Comedy      Crime     NaN   
1746     Ashwini Kalsekar     58,055     Action     Comedy     Horror     NaN   
1747      Frank C. Turner     46,404     Action     Horror     Sci-Fi    5.18   
1748  Juan Antonio Devoto     35,595     Action     Sci-Fi   Thriller     NaN   
1749           Ona Grauer     38,040     Action  Adventure     Horror   10.25   

     Certification  
0                U  
1               UA  
2                U  
3               UA  
4                U  
...            ...  
1745            UA  
1746        UA 16+  
1747             A  
1748           NaN  
1749             A  

[1750 rows x 12 columns]

In [22]:
df1.to_csv('Movies_2.csv')

###### Phase 2

Make two tables and corresponding columns provided in the above CSV files in SQLite DBMS. Insert all data of each CSV file in each of the created tables. Now start querying the table(s) in the  SQL workbench / SQLite database :

Table 1: Sno, MovieName, Director Name, Duration, genre, ratings

1)  Display all the details of movies created by directors Christopher and Matt Reeves.

2) Display all the details of movies with a duration of 140 minutes to 190 minutes.

3) Display all details of movies with ratings above 7 in ascending order.

4) Display all movie names in descending order.

5) Display movie name starts with ‘P’ and their rating is greater than 7.



Table 2: Movie Name, stars, votes, Genre, Gross collection, popularity, Certification

1) Display all movie names with star Arnold Schwarzenegger in ascending order.

2    2) Display all details of the movie with the highest number of votes.

3) Display movie names with gross collections in descending order.

4) Display the gross collection of movies with the star Arnold.

5) Display all details of movies with comedy and action genres.



Make subquery :

1) Display all details from both tables where movie names are the same.

2)   Display all movie names, Director, ratings, and gross collection where the genre is action.

3)      Display all details from both tables with the highest gross collection.

4)      Display all details from both tables with the highest ratings

5)      Display all details from both tables with the lowest gross collection and lowest ratings

In [73]:
# create a databse with name  Movies.db
conn= sqlite3.connect('Movies.db')

# cursor object
cursor = conn.cursor()

In [38]:
# create Table name = movie_1

table1= """ CREATE TABLE movie_1 (
            Serial_no INTEGER NOT NULL,
            Movie_Name VARCHAR(255) ,
            Director_1 VARCHAR(255),
            Director_2 VARCHAR(255),
            Director_3 VARCHAR(255),
            Duration INTEGER,
            Year TEXT,
            Ratings FLOAT,
            Metascore FLOAT,
            PRIMARY KEY (Serial_no,Movie_Name)
        ); """

cursor.execute(table1)
 
print("Table1 is Ready")

Table1 is Ready


In [74]:
# create Table name = movie_2

table2= """ CREATE TABLE movie_2 (
            MoviesName VARCHAR(250),
            Stars_1 VARCHAR(255),
            Stars_2 VARCHAR(255),
            Stars_3 VARCHAR(255),
            Stars_4 VARCHAR(255),
            Votes INTEGER,
            Genre_1 VARCHAR(25),
            Genre_2 VARCHAR(25),
            Genre_3 VARCHAR(25),
            Gross FLOAT,
            Certification VARCHAR(25),
            Popularity INTEGER,
            FOREIGN KEY (MoviesName) REFERENCES movie_1 (Movie_Name)
        ); """

cursor.execute(table2)
 
print("Table2 is Ready")

OperationalError: table movie_2 already exists

In [40]:
# Opening the movie_1.csv file
file = open('Movies_1.csv',encoding='utf-8')
 
# Reading the contents of the

contents = csv.reader(file)
next(contents)
# SQL query to insert data into the table
insert_records = " INSERT INTO movie_1 (Serial_no, Movie_Name, Director_1,Director_2,Director_3, Duration, Year, Ratings, Metascore) VALUES(?,?,?,?,?,?,?,?,?)"
 
# Importing the contents of the file
# into our person table
cursor.executemany(insert_records, contents)
conn.commit()

# SQL query to retrieve all data from the table
select_all = "SELECT * FROM movie_1"
rows = cursor.execute(select_all).fetchall()

cursor.lastrowid

1750

In [75]:
# Opening the movie_2.csv file
file = open('Movies_2.csv',encoding='utf-8')
 
# Reading the contents of the

contents = csv.reader(file)
next(contents)
# SQL query to insert data into the table
insert_records = " INSERT INTO movie_2 (MoviesName, Stars_1,Stars_2,Stars_3,Stars_4, Votes, Genre_1,Genre_2,Genre_3, Gross, Certification, Popularity) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)"
 
# Importing the contents of the file into our table
cursor.executemany(insert_records, contents)
conn.commit()

# SQL query to retrieve all data from the table
select_all = "SELECT * FROM movie_2"
rows = cursor.execute(select_all).fetchall()
conn.close()

cursor.lastrowid

4127

In [42]:
# 1) Display all the details of movies created by directors Christopher and Matt Reeves. 
conn= sqlite3.connect('Movies.db')

# cursor object
mycursor = conn.cursor()
mycursor.execute("SELECT * FROM movie_1 WHERE Director_1  in ('Christopher Nolan','Matt Reev');")
myresult=mycursor.fetchall()

for x in myresult:
    print(x)

(1, 'The Dark Knight', 'Christopher Nolan', '', '', 152, '84', 2008.0, 9.0)
(3, 'Inception', 'Christopher Nolan', '', '', 148, '74', 2010.0, 8.8)
(21, 'The Dark Knight Rises', 'Christopher Nolan', '', '', 164, '78', 2012.0, 8.4)
(41, 'Batman Begins', 'Christopher Nolan', '', '', 140, '70', 2005.0, 8.2)
(129, 'The Batman', 'Matt Reev', '', '', 176, '72', 2022.0, 7.8)
(135, 'Dunkirk', 'Christopher Nolan', '', '', 106, '94', 2017.0, 7.8)
(220, 'Dawn of the Planet of the Apes', 'Matt Reev', '', '', 130, '79', 2014.0, 7.6)
(306, 'War for the Planet of the Apes', 'Matt Reev', '', '', 140, '82', 2017.0, 7.4)
(320, 'Tenet', 'Christopher Nolan', '', '', 150, '69', 2020.0, 7.3)
(502, 'Cloverfield', 'Matt Reev', '', '', 85, '64', 2008.0, 7.0)


In [43]:
# 2) Display all the details of movies with a duration of 140 minutes to 190 minutes.
mycursor.execute("SELECT * FROM movie_1 WHERE Duration BETWEEN 140 and 190;")
myresult= mycursor.fetchall()

for x in myresult:
    print(x)

(0, 'Spider-Man: Across the Spider-Verse', 'Joaquim Dos San', 'Kemp Powers', 'Justin K. Thompson', 140, '86', 2023.0, 9.0)
(1, 'The Dark Knight', 'Christopher Nolan', '', '', 152, '84', 2008.0, 9.0)
(3, 'Inception', 'Christopher Nolan', '', '', 148, '74', 2010.0, 8.8)
(4, 'The Lord of the Rings: The Fellowship of the Ring', 'Peter Jackson', '', '', 178, '92', 2001.0, 8.8)
(5, 'The Lord of the Rings: The Two Towers', 'Peter Jackson', '', '', 179, '87', 2002.0, 8.8)
(8, 'Soorarai Pottru', 'Sudha Kongara', '', '', 153, '', 2020.0, 8.7)
(13, 'Sita Ramam', 'Hanu Raghavapud', '', '', 163, '', 2022.0, 8.6)
(15, 'Gladiator', 'Ridley S', '', '', 155, '67', 2000.0, 8.5)
(18, 'Avengers: Endgame', 'Anthony Ru', 'Joe Russo', '', 181, '78', 2019.0, 8.4)
(19, 'Avengers: Infinity War', 'Anthony Ru', 'Joe Russo', '', 149, '68', 2018.0, 8.4)
(21, 'The Dark Knight Rises', 'Christopher Nolan', '', '', 164, '78', 2012.0, 8.4)
(23, 'Kaithi', 'Lokesh Kanagaraj', '', '', 145, '', 2019.0, 8.4)
(24, 'Asuran', '

In [44]:
# 3) Display all details of movies with ratings above 7 in ascending order.
mycursor.execute("SELECT * FROM movie_1 where Ratings >7.0 ORDER by Ratings;")
myresult= mycursor.fetchall()

for x in myresult:
    print(x)

(52, 'Sherlock Jr.', 'Buster Keaton', '', '', 45, '', 1924.0, 8.2)
(71, 'The General', 'Clyde Bruckman', 'Buster Keaton', '', 67, '', 1926.0, 8.1)
(192, 'Scarface', 'Howard Hawk', 'Richard Rosson', '', 93, '90', 1932.0, 7.7)
(119, 'The Adventures of Robin Hood', 'Michael Curtiz', 'William Keighley', '', 102, '97', 1938.0, 7.9)
(194, 'Key Largo', 'John Huston', '', '', 100, '', 1948.0, 7.7)
(72, 'White Heat', 'Raoul Walsh', '', '', 114, '', 1949.0, 8.1)
(544, 'The War of the Worlds', 'Byron Haskin', '', '', 85, '78', 1953.0, 7.0)
(11, 'Shichinin no samurai', 'Akira Kurosawa', '', '', 207, '98', 1954.0, 8.6)
(70, 'Kakushi-toride no san-akunin', 'Akira Kurosawa', '', '', 139, '89', 1958.0, 8.1)
(29, 'North by Northwest', 'Alfred Hitchcock', '', '', 136, '98', 1959.0, 8.3)
(177, 'The Magnificent Seven', 'John Sturg', '', '', 128, '74', 1960.0, 7.7)
(48, 'Yôjinbô', 'Akira Kurosawa', '', '', 110, '93', 1961.0, 8.2)
(267, 'The Guns of Navarone', 'J. Lee Thompson', '', '', 158, '72', 1961.0, 7

In [45]:
# 4) Display all movie names in descending order.
mycursor.execute("SELECT Movie_Name FROM movie_1 ORDER by Movie_Name DESC;")
myresult= mycursor.fetchall()

for x in myresult:
    print(x)

('Ölümlü Dünya',)
('Æon Flux',)
('xXx: State of the Union',)
('xXx: Return of Xander Cage',)
('xXx',)
('Zoolander 2',)
('Zombieland: Double Tap',)
('Zombieland',)
('Zatôichi',)
('Zathura: A Space Adventure',)
("Zack Snyder's Justice League",)
('Yôjinbô',)
('Your Highness',)
('Young Guns II',)
('Young Guns',)
('You Only Live Twice',)
("You Don't Mess with the Zohan",)
('Yip Man chin chyun',)
('Yip Man 4',)
('Yip Man 3',)
('Yip Man 2',)
('Ying xiong',)
('Yi dai zong shi',)
('Yat goh ho yan',)
('X: First Class',)
('X2',)
('X-Men: The Last Stand',)
('X-Men: Days of Future Past',)
('X-Men: Apocalypse',)
('X-Men Origins: Wolverine',)
('X-Men',)
('Wyatt Earp',)
('Wrongfully Accused',)
('Wrath of the Titans',)
('Wrath of Man',)
('World War Z',)
('Wonder Woman 1984',)
('Wonder Woman',)
('WolfWalkers',)
('Wo hu cang long',)
('Without Remorse',)
('Windtalkers',)
("Willy's Wonderland",)
('Willow',)
('Wild Wild West',)
('Wild Target',)
('Wild Hogs',)
('Wild Card',)
('Whiteout',)
('White House Down'

In [46]:
# 5) Display movie name starts with ‘P’ and their rating is greater than 7
mycursor.execute("SELECT Movie_Name FROM movie_1 WHERE Movie_Name like 'P%' AND Ratings>7.0;")
myresult= mycursor.fetchall()

for x in myresult:
    print(x)

('Paan Singh Tomar',)
('Pirates of the Caribbean: The Curse of the Black Pearl',)
('Per un pugno di dollari',)
('Predator',)
('Ponniyin Selvan: I',)
('Pushpa: The Rise - Part 1',)
('Predestination',)
("Pirates of the Caribbean: Dead Man's Chest",)
('Patriots Day',)
('Point Break',)
('Prey',)
("Pirates of the Caribbean: At World's End",)
('Planet Terror',)
('Payback',)
('Pitch Black',)
('Public Enemies',)
('Pacific Rim',)
('Pineapple Express',)
('Patriot Games',)
('Pandorum',)
("Pete's Dragon",)
('Pirates of the Caribbean: On Stranger Tides',)
('Prince of Persia: The Sands of Time',)
('Penguins of Madagascar',)
('Plane',)
('Pirates of the Caribbean: Dead Men Tell No Tales',)
('Pokémon: Detective Pikachu',)
('Peppermint',)
('Premium Rush',)
('Pain & Gain',)
('Predators',)
('Polar',)
('Predator 2',)
('Paycheck',)
('Proof of Life',)
('Pearl Harbor',)
('Parker',)
('Push',)
('Point of No Return',)
('Project Power',)
('Power Rangers',)
('Pathaan',)
('Punisher: War Zone',)
('Passenger 57',)
('

In [57]:
# 6) Display all movie names with star Arnold Schwarzenegger in ascending order.
mycursor.execute("""SELECT MoviesName FROM movie_2
WHERE (Stars_1 in ('Arnold Schwarzenegge','Arnold Schwarzenegger') or Stars_2 in ('Arnold Schwarzenegge','Arnold Schwarzenegger'));
""")
myresult= mycursor.fetchall()

for x in myresult:
    print(x)

('198',)
('210',)
('696',)
('602',)
('329',)
('247',)
('198',)
('210',)
('696',)
('602',)
('329',)
('247',)
('520',)
('1,050',)
('778',)
('761',)
('1,141',)
('1,346',)
('548',)
('2,501',)
('4,343',)
('624',)
('3,207',)
('518',)
('',)
('4,087',)
('4,524',)
('2,650',)
('933',)


In [58]:
# 7) Display all details of the movie with the highest number of votes.
mycursor.execute("SELECT * FROM movie_2 WHERE Votes=(SELECT max(Votes) FROM movie_2);")
myresult= mycursor.fetchall()

for x in myresult:
    print(x)

('', 'Nefes: Vatan Sagolsun', 'Mete Horozoglu', 'Ilker Kizmaz', 'Baris Bagci', 'Özgür Eren Koç', '34,431', 'Action', 'Drama', 'Thriller', '', '')


In [59]:
# 8) Display movie names with gross collections in descending order.
mycursor.execute("SELECT MoviesName,Gross FROM movie_2 WHERE Gross !='nan' ORDER by Gross DESC;")
myresult= mycursor.fetchall()

for x in myresult:
    print(x)

('2,188', 'Western')
('2,069', 'Western')
('', 'Western')
('2,188', 'Western')
('2,069', 'Western')
('', 'Western')
('1,932', 'Western')
('1,919', 'Western')
('4,091', 'Western')
('3,529', 'Western')
('761', 'Western')
('339', 'War')
('2,542', 'War')
('', 'War')
('', 'War')
('244', 'War')
('1,907', 'War')
('2,568', 'War')
('13', 'War')
('560', 'War')
('2,201', 'War')
('581', 'War')
('', 'War')
('', 'War')
('339', 'War')
('2,542', 'War')
('', 'War')
('', 'War')
('244', 'War')
('1,907', 'War')
('2,568', 'War')
('13', 'War')
('560', 'War')
('2,201', 'War')
('581', 'War')
('', 'War')
('', 'War')
('4,451', 'War')
('', 'War')
('4,598', 'War')
('3,098', 'War')
('4,047', 'War')
('', 'War')
('3,239', 'War')
('363', 'Thriller')
('', 'Thriller')
('', 'Thriller')
('', 'Thriller')
('275', 'Thriller')
('2,001', 'Thriller')
('2,151', 'Thriller')
('', 'Thriller')
('', 'Thriller')
('9', 'Thriller')
('1,042', 'Thriller')
('1,394', 'Thriller')
('3,005', 'Thriller')
('', 'Thriller')
('819', 'Thriller')
('

In [60]:
# 9) Display the gross collection of movies with the star Arnold.
mycursor.execute("""SELECT MoviesName,Gross FROM movie_2
WHERE Stars_1 like '%Arnold%' or  Stars_2 like '%Arnold%' or  Stars_3 like '%Arnold%' or  Stars_4 like '%Arnold%';""")
myresult= mycursor.fetchall()

for x in myresult:
    print(x)

('198', '')
('210', '')
('696', 'Horror')
('602', 'Sci-Fi')
('329', 'Thriller')
('247', 'Fantasy')
('198', '')
('210', '')
('696', 'Horror')
('602', 'Sci-Fi')
('329', 'Thriller')
('247', 'Fantasy')
('520', 'Thriller')
('1,889', '')
('1,050', 'Thriller')
('778', 'Comedy')
('761', 'Western')
('1,141', 'Sci-Fi')
('1,346', '')
('548', 'Crime')
('650', 'Sci-Fi')
('2,501', 'Thriller')
('4,343', 'Crime')
('624', 'Fantasy')
('3,207', 'Sci-Fi')
('518', 'Horror')
('', 'Drama')
('4,087', 'Thriller')
('4,524', 'Thriller')
('2,650', 'Fantasy')
('933', '')


In [61]:
# 10) Display all details of movies with comedy and action genres.
mycursor.execute("""SELECT * FROM movie_2
WHERE  Genre_1 in ('Action','Comedy') AND Genre_2 in ('Action','Comedy') or Genre_3 in ('Action','Comedy');""")
myresult= mycursor.fetchall()

for x in myresult:
    print(x)

('1', 'Spider-Man: Across the Spider-Verse', 'hameik Moore', 'Hailee Steinfeld', 'Brian Tyree Henry', 'Luna Lauren Velez', '1,25,082', 'Animation', 'Action', 'Adventure', '', 'U')
('5', 'Spider-Man: Into the Spider-Verse', 'hameik Moore', 'Jake Johnson', 'Hailee Steinfeld', 'Mahershala Ali', '5,88,262', 'Animation', 'Action', 'Adventure', '190.24', 'U')
('1,232', 'Mononoke-hime', 'YÃ´ji Matsud', 'Yuriko Ishida', 'YÃ»ko Tanaka', 'Billy Crudup', '4,07,836', 'Animation', 'Action', 'Adventure', '2.38', 'U')
('2,048', 'Kimetsu no Yaiba: Mugen Ressha-Hen', 'Natsuki Hanae', 'Akari KitÃ´', 'Yoshitsugu Matsuoka', 'Hiro Shimono', '64,898', 'Animation', 'Action', 'Adventure', '47.7', 'UA')
('4,705', 'Gangs of Wasseypur', 'Manoj Bajpayee', 'Nawazuddin Siddiqui', 'Tigmanshu Dhulia', 'Richa Chadha', '99,502', 'Action', 'Comedy', 'Crime', '', 'A')
('', 'Sherlock Jr.', 'Buster Keaton', 'Kathryn McGuire', 'Joe Keaton', 'Erwin Connelly', '52,631', 'Action', 'Comedy', 'Romance', '0.98', '')
('744', 'Lock

In [86]:
# 11) Display all details from both tables where movie names are the same.
mycursor.execute("""SELECT * FROM movie_1 
JOIN movie_2
on movie_1.Movie_Name=movie_2.MoviesName
WHERE movie_1.Movie_Name in (select Movie_Name from (SELECT Movie_Name , count(*) as count from movie_1
group by Movie_Name
HAVING count>1)) ;""")
myresult= mycursor.fetchall()

for x in myresult:
    print(x)

In [77]:
# 12) Display all movie names, Director, ratings, and gross collection where the genre is action.
mycursor.execute("""SELECT Movie_Name,Director_1,Director_2,Director_3,Ratings,movie_2.Gross FROM movie_1 
JOIN movie_2
on movie_1.Movie_Name=movie_2.MoviesName
WHERE Genre_1='Action' or Genre_2='Action' or Genre_3='Action';""")
myresult= mycursor.fetchall()

for x in myresult:
    print(x)

('9', 'Shane Ack', '', '', 2009.0, 'Thriller')
('9', 'Shane Ack', '', '', 2009.0, 'Thriller')
('9', 'Shane Ack', '', '', 2009.0, 'Thriller')


In [87]:
# 13) Display all details from both tables with the highest gross collection.
mycursor.execute("""SELECT * FROM movie_1 
JOIN movie_2
on movie_1.Movie_Name=movie_2.MoviesName
WHERE movie_2.Gross=(SELECT max(movie_2.Gross) FROM movie_2 WHERE movie_2.Gross!='nan');""")
myresult= mycursor.fetchall()

for x in myresult:
    print(x)

In [88]:
# 14) Display all details from both tables with the highest ratings.
mycursor.execute("""SELECT * FROM movie_1 
JOIN movie_2
on movie_1.Movie_Name=movie_2.MoviesName
WHERE movie_1.Ratings=(SELECT max(movie_1.Ratings) FROM movie_1);""")
myresult= mycursor.fetchall()

for x in myresult:
    print(x)

In [89]:
# 15) Display all details from both tables with the lowest gross collection and lowest ratings.
mycursor.execute("""SELECT * FROM movie_1 
JOIN movie_2
on movie_1.Movie_Name=movie_2.MoviesName
WHERE movie_2.Gross=(SELECT min(movie_2.Gross) FROM movie_2)
ORDER by movie_1.Ratings LIMIT 1;""")
myresult= mycursor.fetchall()

for x in myresult:
    print(x)